version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  allow:
    - dependency-type: "all"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
