version: '3'
services:
  buguette-server:
    build: .
    ports:
      - "80:80"
      - "443:443"
    restart: always
    tty: true
    volumes:
      - ./buguette-https.conf/:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/:/etc/letsencrypt
      - ./.certbot:/var/www/certbot
