version: '3'
services:
  buguette-server:
    image: nginx:1.16.0
    ports:
      - "80:80"
      - "443:443"
    tty: true
    volumes:
      - ./buguette-https.conf/:/etc/nginx/conf.d/default.conf
      - ./dist/:/buguette/dist/
      - /root/letsencrypt/:/etc/letsencrypt
  buguette-build:
    build: .
    volumes:
      - ./dist/:/buguette/dist/
    command: ["npm", "run", "build"]
    tty: true
