export class StaticData {
  public static readonly PRODUCTS =
  {"Office Canvas Document Editor": { name: "Documents", color: "#cbcbff", active: false, realName: "Office Canvas Document Editor" },
  "Office Canvas Spreadsheet Editor": { name: "Spreadsheets", color: "#c5ffc5", active: false, realName: "Office Canvas Spreadsheet Editor" },
  "Office Canvas Presentation Editor": { name: "Presentations", color: "#ffa7a7", active: false, realName: "Office Canvas Presentation Editor" },
  "documenteditors plugins": { name: "Plugins", color: "#ff8ee2", active: false, realName: "documenteditors plugins" },
  "DocumentBuilder": { name: "Builder", color: "#feffba", active: false, realName: "DocumentBuilder" }};

  public static readonly SEVERITIES =
  {"critical": { name: "Critical", realName: "critical", addition: ["blocker"], color: "#ff0000" },
  "major": { name: "Major", realName: "major", color: "#ff8922" },
  "normal": { name: "Normal", realName: "normal", color: "#000000" },
  "minor": { name: "Minor", realName: "minor", color: "#000000" },
  "trivial": { name: "Trivial", realName: "trivial", color: "#000000" },
  "enhancement": { name: "Enhancement", realName: "enhancement", isFeature: true, color: "#30ac09" }};

  public static STATUSES =
  {"NEW": { name: "New/Assigned", realName: "NEW", addition: ["ASSIGNED"], active: false },
  "FIXED": { name: "Fixed", realName: "FIXED", active: false },
  "VERIFIED": { name: "Verified", realName: "VERIFIED", active: false },
  "REOPENED": { name: "Reopen", realName: "REOPENED", active: false }};

  public static PRIORITIES =
  {"P1": { name: "P1", realName: "P1" },
  "P2": { name: "P2", realName: "P2" },
  "P3": { name: "P3", realName: "P3" },
  "P4": { name: "P4", realName: "P4" },
  "P5": { name: "P5", realName: "P5" }};

  public static USERS =
  [{"username":"HolmesPixel", "name": "Aleksandr Yarovoy"},
  {"username":"Alex.Bannov", "name": "Alex Bannov", avatar: true},
  {"username":"Alexander.Igoshin", "name": "Alexander Igoshin"},
  {"username":"Alexander.Zozulya", "name": "Alexander Zozulya"},
  {"username":"Alexander.Trofimov", "name": "Alexander Trofimov", avatar: true},
  {"username":"Alexander.Vnuchkov", "name": "Alexander Vnuchkov", avatar: true},
  {"username":"Alexander.Yuzhin", "name": "Alexander Yuzhin", avatar: true},
  {"username":"Alexey.Kostenko", "name": "Alexey Kostenko", avatar: true},
  {"username":"Alexey.Matveev", "name": "Alexey Matveev"},
  {"username":"Alexey.Golubev", "name": "Alexey Golubev", avatar: true},
  {"username":"alexm", "name": "Alexey Miсheev", avatar: true},
  {"username":"Alexey.Musinov", "name": "Alexey Musinov", avatar: true},
  {"username":"Alexey.Safronov", "name": "Alexey Safronov", avatar: true},
  {"username":"Alina.Safonova", "name": "Alina Safonova"},
  {"username":"Alina.Krivosheeva", "name": "Alina Krivosheeva"},
  {"username":"Anastasia.Markelova", "name": "Anastasia Markelova", avatar: true},
  {"username":"Anastasiia.Reagan", "name": "Anastasiia Reagan"},
  {"username":"Andrew.Panov", "name": "Andrew Panov", avatar: true},
  {"username":"Andrey.Bursian", "name": "Andrey Bursian"},
  {"username":"Andrey.Sviridov", "name": "Andrey Sviridov"},
  {"username":"Andrey.Dudov", "name": "Andrey Dudov"},
  {"username":"andrey.grishagin", "name": "Andrey Grishagin"},
  {"username":"andrey.savihin", "name": "Andrey Savihin", avatar: true},
  {"username":"Anna.Korshul", "name": "Anna Korshul"},
  {"username":"Anna.Medvedeva", "name": "Anna Medvedeva", avatar: true},
  {"username":"Anton.Kolpakov", "name": "Anton Kolpakov"},
  {"username":"Artem.Antipkin", "name": "Artem Antipkin"},
  {"username":"bryan.gono", "name": "Bryan Gono"},
  {"username":"Daniil.Senkiv", "name": "Daniil Senkiv"},
  {"username":"denis.spitsyn.4test", "name": "Denis Test"},
  {"username":"Denis.Myshaev", "name": "Denis Myshaev", avatar: true},
  {"username":"Denis.Spitsyn", "name": "Denis Spitsyn", avatar: true},
  {"username":"Denis.Yudin", "name": "Denis Yudin"},
  {"username":"dmitry.gubanov", "name": "Dmitry Gubanov"},
  {"username":"Dmitry.Isakov", "name": "Dmitry Isakov"},
  {"username":"Dmitry.Rotatyy", "name": "Dmitry Rotatyy", avatar: true},
  {"username":"Dmitry.Vanyukov", "name": "Dmitry Vanyukov"},
  {"username":"Dmitry.Kolesnikov", "name": "Dmitry Kolesnikov", avatar: true},
  {"username":"egor.rozhnetsov", "name": "Egor Rozhentsov"},
  {"username":"Egor.Zorin", "name": "Egor Zorin", avatar: true},
  {"username":"Ekaterina.Heidel", "name": "Ekaterina Heidel", avatar: true},
  {"username":"Jekaterina.Osipova", "name": "Ekaterina Osipova", avatar: true},
  {"username":"elena.belova", "name": "Elena Belova"},
  {"username":"Elena.Subbotina", "name": "Elena Subbotina"},
  {"username":"Evgenia.Olshanskaja", "name": "Evgenia Olshanskaja"},
  {"username":"evgeny.katyshev", "name": "Evgeny Katyshev", avatar: true},
  {"username":"Galina.Goduhina", "name": "Galina Goduhina", avatar: true},
  {"username":"githubbot", "name": "Github Bot"},
  {"username":"Igor.Kolpakov", "name": "Igor Kolpakov"},
  {"username":"Igor.Zotov", "name": "Igor Zotov", avatar: true},
  {"username":"Ilja.Kirillov", "name": "Ilja Kirillov", avatar: true},
  {"username":"Ilya.Oleshko", "name": "Ilya Oleshko"},
  {"username":"ilya.sobolev", "name": "Ilya Sobolev"},
  {"username":"Irina.Malysheva", "name": "Irina Malysheva"},
  {"username":"Irina.Sanaeva", "name": "Irina Sanaeva"},
  {"username":"ivan.danilov", "name": "Ivan Danilov"},
  {"username":"Ivanov.Alexey", "name": "Ivanov Alexey"},
  {"username":"Julia.Svinaryova", "name": "Julia Svinaryova"},
  {"username":"Julia.Radzhabova", "name": "Julia Radzhabova", avatar: true},
  {"username":"Kate.Osipova", "name": "Kate Osipova"},
  {"username":"khromov.nikita", "name": "Khromov Nikita"},
  {"username":"Kirill.Solodovnikov", "name": "Kirill Solodovnikov"},
  {"username":"Kirill.Volkov", "name": "Kirill Volkov"},
  {"username":"Lev.Bannov", "name": "Lev Bannov", avatar: true},
  {"username":"Maksim.Bugrov", "name": "Maksim Bugrov"},
  {"username":"Maksim.Matveev", "name": "Maksim Matveev"},
  {"username":"maksim.osipov", "name": "Maksim Osipov"},
  {"username":"Maksim.Sorokin", "name": "Maksim Sorokin"},
  {"username":"Margarita.Bubnova", "name": "Margarita Bubnova"},
  {"username":"Margarita.Kitaeva", "name": "Margarita Kitaeva"},
  {"username":"Marina.Matveeva", "name": "Marina Matveeva"},
  {"username":"Maxim.Kadushkin", "name": "Maxim Kadushkin", avatar: true},
  {"username":"mikhail.efremov", "name": "Mikhail Efremov"},
  {"username":"Mikhail.Skorodelov", "name": "Mikhail Skorodelov"},
  {"username":"Mikhail.Grunin", "name": "Mikhail Grunin", avatar: true},
  {"username":"n.knyazeva118", "name": "Nadezda knyazeva", avatar: true},
  {"username":"Nastya.Lapteva", "name": "Nastya Lapteva"},
  {"username":"natalia.pistsova", "name": "Natalia Pistsova"},
  {"username":"Natalya.Dunina", "name": "Natalya Dunina"},
  {"username":"Nikita.Privalov", "name": "Nikita Privalov"},
  {"username":"nikita.antipin", "name": "Nikita Antipin"},
  {"username":"nikolay.pugachev", "name": "Nikolay Pugachev", avatar: true},
  {"username":"nikolaynikcher", "name": "Nikolay Rechkin"},
  {"username":"oleg.gonchar", "name": "Oleg Gonchar"},
  {"username":"Oleg.Korshul", "name": "Oleg Korshul", avatar: true},
  {"username":"olga.grunina", "name": "Olga Grunina"},
  {"username":"Olga.Nesterova", "name": "Olga Nesterova"},
  {"username":"Olga.Savosina", "name": "Olga Savosina"},
  {"username":"Olga.Golubeva", "name": "Olga Golubeva"},
  {"username":"Olga.Tyumenkova", "name": "Olga Tyumenkova"},
  {"username":"Pavel.Bannov", "name": "Pavel Bannov", avatar: true},
  {"username":"shockwavenn", "name": "Pavel Lobashov", avatar: true},
  {"username":"Roman.Demidov", "name": "Roman Demidov"},
  {"username":"Roman.Neviditsyn", "name": "Roman Neviditsyn"},
  {"username":"Semen.Bezrukov", "name": "Semen Bezrukov"},
  {"username":"Serge.Seyfetdinov", "name": "Serge Seyfetdinov"},
  {"username":"sergey.leushkin", "name": "Sergey Leushkin"},
  {"username":"Sergey.Kirillov", "name": "Sergey Kirillov", avatar: true},
  {"username":"Sergey.Konovalov", "name": "Sergey Konovalov", avatar: true},
  {"username":"Sergey.Linnik", "name": "Sergey Linnik", avatar: true},
  {"username":"Sergey.Luzyanin", "name": "Sergey Luzyanin", avatar: true},
  {"username":"Sergey.Malkin", "name": "Sergey Malkin"},
  {"username":"Sergey.Shiryaev", "name": "Sergey Shiryaev"},
  {"username":"Svetlana.Shestakova", "name": "Svetlana Shestakova"},
  {"username":"Svetlana.Maleeva", "name": "Svetlana Maleeva"},
  {"username":"Tatiana.Kochedykova", "name": "Tatiana Kochedykova", avatar: true},
  {"username":"Tatiana.Tyulyutova", "name": "Tatiana Tyulyutova"},
  {"username":"shockwavenn+test", "name": "test lobashov"},
  {"username":"teamlab.ruby", "name": "testing-github-warden"},
  {"username":"TestrailBugLookup", "name": "TestrailBugLookup"},
  {"username":"vadim.kulkov", "name": "vadim kulkov"},
  {"username":"Viktoriya.Vikhareva", "name": "Viktoriya Vikhareva"},
  {"username":"Vlada.Leshcheva", "name": "Vlada Leshcheva"},
  {"username":"Vladimir.Gorshenkov", "name": "Vladimir Gorshenkov"},
  {"username":"Vladimir.Voronin", "name": "Vladimir Voronin"}]
}

