name: ci
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check markdown files using `markdownlint`
      run: |
        npm install -g markdownlint-cli
        markdownlint *.md
